# Generated by Django 3.2.25 on 2024-11-30 02:06

from django.db import migrations, models
import django.db.models.deletion
import pacientes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[pacientes.models.validate_nombre])),
                ('especie', models.CharField(max_length=50)),
                ('edad', models.IntegerField(validators=[pacientes.models.validate_edad])),
                ('raza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedades', models.TextField()),
                ('tratamientos', models.TextField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.veterinario')),
            ],
        ),
    ]
