# Generated by Django 3.2.25 on 2024-11-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='especie_otra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(choices=[('canina', 'Canina'), ('felina', 'Felina'), ('ave', 'Ave'), ('otros', 'Otros')], max_length=50),
        ),
    ]
