# Generated by Django 3.2.25 on 2024-12-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20241129_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='gravedad',
            field=models.CharField(choices=[('emergencia', 'Emergencia'), ('moderada', 'Moderada'), ('leve', 'Leve')], default='leve', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_dueño',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
