# Generated by Django 3.2.25 on 2024-12-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20241202_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nombre_dueño',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True),
        ),
    ]
