# Generated by Django 3.2.25 on 2024-12-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_nombre_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='unidad_edad',
            field=models.CharField(choices=[('años', 'Años'), ('meses', 'Meses')], default='años', max_length=5),
        ),
    ]
